### ISSUE TITLE
Support url params to open specific workspaces

### ISSUE THREAD

**Issue by wilkerlucio** [nubank/workspaces#20]

**Comment by felipethome** [comment]
I opened a PR with a solution for this issue: https://github.com/nubank/workspaces/pull/54

Though I think it would be nice to discuss this solution before merging the PR.

**Problem statement: we can't open a specific workspace through the URL**

### Solution 1: Query Parameters
I like the query parameter because it allows for a very small solution. With just a few lines we are able to open the ws and we don't require any other lib to do so.
Disadvantages: the URL doesn't reflect the state of the interface, we just use the query parameter to open the initial ws, but after changing workspaces (by clicking on another tab for example) the URL will not be changed.

### Solution 2: Use a proper router
With a router like secretary we use hash `#` prefixed routes and let the route dispatch function to open the desired workspace.

Disadvantages: This solution requires more code because we would like to have the tab and menu links to update the URL and use the router to update the interface calling the `open-workspace` fulcro mutation. This solution also has the problem of the need to import another library (like secretary) that may conflict with user existing ones.

I prefer solution 1, but I feel it is important to discuss this solution because once we define the URL format (query parameter or hash) we are going to stick with it.
